[package]
name = "omnideps"
description = "A language-agnostic code analyzer using tree-sitter"
version = "0.1.0"
edition = "2024"
default-run = "omnideps"

[dependencies]
tree-sitter = "0.26.8"
tree-sitter-c = "0.24"
tree-sitter-cpp = "0.23"
tree-sitter-java = "0.23"
tree-sitter-python = "0.23"
tree-sitter-rust = "0.24"

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
clap = { version = "4.5", features = ["derive"] }
walkdir = "2.5"
anyhow = "1.0"
serde_yaml = "0.9.34"
csv = "1.3"
axum = "0.8.9"
tokio = { version = "1.53.1", features = ["full"] }
rust-embed = "8.12.0"
mime_guess = "2.0.5"

[[bin]]
name = "omnideps"
path = "src/main.rs"
